# Use Node.js 18 as the base image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy all other files into the container
COPY . .

# Expose the port your app runs on (e.g., 3000)
EXPOSE 9090

# Start the application
CMD ["node", "server.mjs", ".env.cert"]
